### ISSUE TITLE
Project is not starting

### ISSUE THREAD

**Issue by rohailiqbal** [AhmedMah/ClinicManagement#2]
Hi,
I am trying to run the project but it is not starting.
Following page appears:
![image](https://user-images.githubusercontent.com/30309646/51890271-76c62900-23bd-11e9-92bb-b55869fb6428.png)

I did run the migration commands as you mentioned.
Please help to resolve the issue.

I was running this project in VS2017.
it worked fine in VS2015

**Comment by saadiii125** [comment]
run this in the Package Manager Console:

Update-Package Microsoft.CodeDom.Providers.DotNetCompilerPlatform -r
